### ISSUE TITLE
Отваливается соединение при отправке сообщения

### ISSUE THREAD

**Issue by strangerAlexander** [morozovsk/websocket#10]
Добрый день. Не поможете советом?

Есть небольшая проблема. Может быть, Вы с подобным уже сталкивались, и мне не придётся заново изобретать велосипед.

Всё установил, запустил, даже подключился. Но есть одно но, сообщения на клиент приходят через раз и какие-то обрезанные. Причём после отдачи этого обрезанного сообщения падает соединение с сервером. Клиент есть здесь: http://boroviha.dev.ooosis.com/example/index.html

В Вашем коде практически ничего не менял, только в методе ChatWebsocketDaemonHandler::onOpen убрал второй параметр.

**Comment by morozovsk** [comment]
в консоль или в файл nohup должны писаться ошибки, но скорее всего нужно вернуть второй параметр

**Comment by strangerAlexander** [comment]
В том и дело, что ошибок никаких нет. А если вернуть параметр, то появляется: 

"Strict standards: Declaration of morozovsk\websocket\examples\chat\server\ChatWebsocketDaemonHandler::onOpen() should be compatible with morozovsk\websocket\Daemon::onOpen($connectionId) in /home/bitrix/webserver/morozovsk/websocket/examples/chat/server/ChatWebsocketDaemonHandler.php on line 7"

**Comment by morozovsk** [comment]
исправил. проблема была в том что на гитхабе исправил, а в композер не залил
