### ISSUE TITLE
Тестирование нагрузки

### ISSUE THREAD

**Issue by k1b0rg** [morozovsk/websocket#11]
Добрый день! В первую очередь хотел выразить слова благодарности Вам за вашу библиотеку, используем в боевых условиях, очень круто!

По мере роста проекта уперлись конечно же в ограничение 1024 коннекта. Переписываем на вариант с воркерами, и тут возникает такой вопрос: а чем/как можно все это дело протестировать? В самой первой вашей статье на хабре Вы писали, что локально подавали одновременно 10к соединений, хотелось бы протестировать также работу с воркерами.

**Comment by morozovsk** [comment]
Здравствуйте. Большое спасибо за отзыв!
Вместе с библиотекой идёт файл Test.php - он открывает 1.5к соединений.
Для тестирования я просто запускаю его несколько раз в разных вкладках терминала, например, если запустить его 10 раз, то будет открыто 15к соединений.
Для поддержки не обязательно всё переписывать на воркеры, достаточно установить pecl/event или pecl/libevent и в конфиге указать 'eventDriver' => 'event' или 'eventDriver' => 'libevent'

**Comment by k1b0rg** [comment]
Благодарю за наводку про PECL Event.
Сейчас поставили его, начали тестировать, результаты такие:
У нас два демона вебсокетов, один с локальным сокетом, а второй нет (чат).
Так вот, демон без локального сокета ведет себя замечательно, запускаю несколько Test.php, при этом ещё порядка 60-80 живых соединений, при отправке сообщений в чат - все доходит без задержек.
Иначе дела обстоят дела с демоном, у которого имеется локальный сокет. Цель нашего демона вебсокетов - оповещать о новой информации, переключаем его на 'eventDriver' => 'event', далее другой демон (не вебсокетов) по мере обработки информации пишет в локальный сокет таким способом:
$instance = stream_socket_client ($localsocket, $errno, $errstr);
И наблюдаем такую картинку - некоторые сообщения при записи в локальный сокет моментально приходят на демон вебсокетов и разлетаются дальше килентам, а некоторые (чуть побольше размером) - не сразу приходят, а с некоторой задержкой. Возвращаемся на socket_select - все работает замечательно, любых размером информация быстро доставляется через локальный сокет.

Вопрос собственно в чем, не сталкивались ли Вы при тестировании с такой рода "задержкой" при записи в локальный сокет, если  используется PECL Event?
Не знаем откуда начать копать, т.к при возврате на socket_select все летает при 400-600 живых коннектов.

**Comment by morozovsk** [comment]
информации много, но она запутанная :) Итак, у вас всего 2 демона или 3? Как я понял ситуацию:
Первый демон с локальным сокетом
Второй демон без локального сокета
Третий демон использует конструкцию $instance = stream_socket_client ($localsocket, $errno, $errstr); чтобы передать данные в локальный сокет первого демона.
Все демоны используют 'eventDriver' => 'event'.

Если всё так, то лучше для записи из третьего демона использовать sendToMaster() вместо $instance = stream_socket_client ($localsocket, $errno, $errstr); предварительно указав в конфиге 'master' => 'локальный_сокет_первого_демона'

**Comment by k1b0rg** [comment]
Да, вы все верно поняли, только небольшое уточнение по поводу третьего демона
Третий демон - это не демон вебсокетов, это просто бесконечный while, перед которым сначала подключаемся к локальному сокету используя конструкцию $instance = stream_socket_client ($localsocket, $errno, $errstr);
а далее, уже в while, пишем в него.
Немного потестировав, нашли проблему, ей оказалась константа  SOCKET_BUFFER_SIZE = 1024 в классе GenericEvent.
Как выяснилось, мы периодически записывали в локальный сокет данные размером ~ 3000.
Увеличили размер константы SOCKET_BUFFER_SIZE  и все заработало (НО, повторюсь, на socket_select все работало на стандартных настройках)
На данный момент полет нормальный, тестировали файлом Test.php - тоже все отлично!

**Comment by morozovsk** [comment]
>мы периодически записывали в локальный сокет данные размером ~ 3000

Интересует с помощью какой функции вы записывали туда данные? Если вы использовали функцию fwrite(), то проверяли ли её ответ на количество байт которых было успешно отправлено, чтобы потом отправить данные которые не были отправлены?
Например:
$written = fwrite($connect, $string);//количество записанных байт в сокет
$string = substr($string, $written);//оставшаяся часть строки
if ($string) {
   stream_select(null, [$connect], [], null);
   $written = fwrite($connect, $string);
}

**Comment by k1b0rg** [comment]
Для записи использовали функцию fwrite, не проверяли, сколько ф-я записла, сейчас проверили, результаты такие:
Записываем строку длиной 2858, при любом значении SOCKET_BUFFER_SIZE (512/1204/4096) в классе GenericEvent, fwrite возвращает 2858 (непонятно, с чего бы это вдруг?)
Попробовали принудительно разбить на части так: fwrite($connecct, $string, 1024)
Данные прилетают через раз.
Странно, почему себя так fwrite ведет?

P.S Debian 8, PHP 5.6.14, event 1.11.1, libcurl4-openssl-dev
