### ISSUE TITLE
PHP7

### ISSUE THREAD

**Issue by k1b0rg** [morozovsk/websocket#12]
Добрый день!
Не подскажите, нет ли в планах адаптации библиотеки под PHP7? Или библиотека в текущем состоянии полностью совместима?
К тому же, буквально вчера (29.02.2016) вышла стабильная версия Event с поддержкой PHP7 - https://pecl.php.net/package/event 
Во второй версии, судя по ченжлогу поправили утечки памяти (не знаю, может только у меня так, но на php 5.6.x с event после 14-15к коннектов, последующие коннекты начинают приниматься 1 через 5, перезапускаешь демона - все как по маслу, возвращаешься на socket_select - проблем нет.

**Comment by morozovsk** [comment]
Здравствуйте. На пхп 7 по идее и так должно работать, но нужно тестировать - как раз в ближайшие дни планировал попробовать.

**Comment by morozovsk** [comment]
На пхп 7 уже давно протестировал - работает, всё забывал здесь отписаться.
Описанная проблема не воспроизводится - открывал 30к соединений одновременно
