### ISSUE TITLE
Падение мастера и несуществующий connectionId в buffer'ах

### ISSUE THREAD

**Issue by anggrybanana** [morozovsk/websocket#13]
Проблема 1:
в Generic.php (для любых модулей) есть функции _read, _write, close которые могут заэррорить и сказать Call to undefined function read/write/disable on null, решается добавлением
`if(!isset($this->buffers[$connectionId])) return;`
в каждую из функций

Проблема 2:
Event, связанная с этой библиотекой, через время (прим. 15мин) $this->getIdByConnection($this->_master) отдает 0 (GenericEvent.php), думая что это не мастер, передача данных в функцию onMasterMessage не происходит, решил для себя добавлением возле 
`$this->onServiceMessage($connectionId, $data); `
этого
`$this->onMasterMessage($data);`

Но лучше ждать оф. фикс от автора

**Comment by anggrybanana** [comment]
Проблема в том что мастер закрывает соединение, как оказалось. Что-то с этим сделать можно?

**Comment by morozovsk** [comment]
Что происходит с мастером после закрытия соединения? Выдаёт какие-то ошибки? как запускаются мастер и воркер? 
хорошо бы увидеть код, который их обработчиков

**Comment by anggrybanana** [comment]
Код взят из примеров с чатом, падение происходит только на Event'е, на простых stream'ах всё отлично. Пробовал и новые и старые версии. Мастер просто отключается, ошибок не выдает.

**Comment by anggrybanana** [comment]
PHP Notice:  Uninitialized string offset: 1 in websocket/WebsocketDaemon.php on line 152
`$secondByteBinary = sprintf('%08b', ord($data[1]));`

**Comment by morozovsk** [comment]
у вас какая-то старая версия, в текущей версии перед кодом, который вызывает ошибку стоит код: if (strlen($data) < 2) return false; 
а указанная строка уже находится не на 152, а на 175 строке кода
