### ISSUE TITLE
Possible logic error & websocket standards

### ISSUE THREAD

**Issue by sebstyle** [morozovsk/websocket#17]
**Possible logic error**
I did not actually run your code but from looking at it..
And I might be wrong because i really do not understand the Russian language, in that case i apologize..
Here goes..
`Daemon.php`
```
protected function _onOpen($connectionId) {
  $this->_handshakes[$connectionId] = '';//отмечаем, что нужно сделать рукопожатие
}
```
```
protected function _onMessage($connectionId) {
  if (isset($this->_handshakes[$connectionId])) {
    if ($this->_handshakes[$connectionId]) {//если уже было получено рукопожатие от клиента
      return;//то до отправки ответа от сервера читать здесь пока ничего не надо
    }
    if (!$this->_handshake($connectionId)) {
      $this->close($connectionId);
    }
  } else {
    while (($data = $this->_decode($connectionId)) && mb_check_encoding($data['payload'], 'utf-8')) {//декодируем буфер (в нём может быть несколько сообщений)
      $this->onMessage($connectionId, $data['payload'], $data['type']);//вызываем пользовательский сценарий
    }
  }
}
```
The above 2 methods are called from the `while` loop `GenericSelect->start()` in `GenericSelect.php`.
```
...
if ($this->_handshakes[$connectionId]) {//если уже было получено рукопожатие от клиента
  return;//то до отправки ответа от сервера читать здесь пока ничего не надо
}
...
```
The `$this->_handshakes[$connectionId]` contains an empty string ('') which evaluates to `true`.
This causes the function to `return` and actual handshake `$this->_handshake($connectionId)` to never happen..
You probably meant to check for:
```
...
if ($this->_handshake($connectionId)) {//если уже было получено рукопожатие от клиента
  return;//то до отправки ответа от сервера читать здесь пока ничего не надо
}
...
```
That would evaluate to `true` on an incomplete handshake and `return` to continue reading until a complete handshake has been received..

**Websocket standards**
`Daemon.php`
```
protected function _onMessage($connectionId) {
  ...
    if (!$this->_handshake($connectionId)) {
      $this->close($connectionId);
    }
  ...
}
```
The connection simply gets closed while the websocket standard states that a proper response should be written to the client.
For example when the handshake does not contain `Sec-WebSocket-Key` the proper response to write to the client would be `"HTTP/1.1 400 Bad Request\r\n\r\n"`
In fact the handshake should be checked for many more errors for example when `Sec-WebSocket-Version` is incompatible the proper response to write to the client would be `"HTTP/1.1 426 Upgrade Required\r\nSec-WebSocketVersion: 13\r\n\r\n"`

A possible solution would be to:
`Daemon.php`
```
protected function _onMessage($connectionId) {
  if (isset($this->_handshakes[$connectionId])) {
    if ($this->_handshake($connectionId)) {//если уже было получено рукопожатие от клиента
      return;//то до отправки ответа от сервера читать здесь пока ничего не надо
    }
    if ($this->_handshakes[$connectionId] != false && !$this->_handshake($connectionId)) {
     $this->_handshakes[$connectionId] = false;
    }
  } else {
    while (($data = $this->_decode($connectionId)) && mb_check_encoding($data['payload'], 'utf-8')) {//декодируем буфер (в нём может быть несколько сообщений)
      $this->onMessage($connectionId, $data['payload'], $data['type']);//вызываем пользовательский сценарий
    }
  }
}
```
Do not call `$this->close($connectionId)` strait away but set `$this->_handshakes[$connectionId]` to `false`.

`GenericSelect.php`
```
...
  if ($write) {
    foreach ($write as $client) {
      if (is_resource($client)) {//проверяем, что мы его ещё не закрыли во время чтения
        $this->_sendBuffer($client);
        if ($this->_handshakes[$client] == false) { $this->close($client); }
      }
    }
  }
...
```
On the next `while` loop `stream_select($read, $write, $except, null);` will pick up the `_write` buffer containing the error and once it has written the proper response check `$this->_handshakes[$client]` for `false` and close the connection there..

That's what i've found so far..
I like your coding style, keep up the good work!

**Comment by morozovsk** [comment]
Thank you very much for your feedback. You did a really deep code analysis and found there are some problems.

1) 
```
if ($this->_handshakes[$connectionId]) {//если уже было получено рукопожатие от клиента
    return;//то до отправки ответа от сервера читать здесь пока ничего не надо
}
```
This code is never executed because the `$this->_handshakes[$connectionId]` contains an empty string ('') which evaluates to **false** not **true**. I will remove this code.

2) 
```
if (!$this->_handshake($connectionId)) {
    $this->close($connectionId);
}
```
This code close connection only if all headers received:
```
if (!strpos($this->_read[$connectionId], "\r\n\r\n")) {
    return true;
}
```

3) 
```
if ($write) {
    foreach ($write as $client) {
      if (is_resource($client)) {//проверяем, что мы его ещё не закрыли во время чтения
        $this->_sendBuffer($client);
        if ($this->_handshakes[$client] == false) { $this->close($client); }
      }
    }
  }
```
This code is not enough to send the data from the buffer to the client, you must also make sure that the data is completely gone, and the buffer is empty.
I will fix it in the next version.

4) I will translate all comments to English :)

Thank you again for your review.

**Comment by sebstyle** [comment]
You were right, that empty string does evaluate to false :)
Also, keep in mind that until handshake is returned to client you would have to redirect normal messages to a separate buffer that gets written once the handshake is completed.
Otherwise the write buffer may contain a message before it contains the handshake reply.
This is why so many websocket classes maintain a client object to keep track of such things.

**Comment by morozovsk** [comment]
Daemon.php:
```
protected function sendToClient($connectionId, $data, $type = 'text') {
        if (!isset($this->_handshakes[$connectionId])) {
            $this->_write($connectionId, $this->_encode($data, $type));
        }
    }
```
until I do not finish a handshake with the client all messages ignored

**Comment by sebstyle** [comment]
Then it was a logic error on my behalf :)
I do apologize for that..
Latest websocket specs also no longer mentions http error codes so i guess all is good.

I am having some problems implementing status codes in the close frame as per the latest specs.
Is there any way i can contact you about this issue?
Perhaps we can work together towards a solution that will also work in your project..
You can send an email to the info@ the website address domain specified in my profile.

Thanks in advance!
