### ISSUE TITLE
Вопрос о наследовании и Demon

### ISSUE THREAD

**Issue by Sirgalas** [morozovsk/websocket#18]
стал изучать Ваш demon и заметил что он наследуется от класса Generic но самого класса не нашел не нашел так же и следующих свойств 
1. $this->clients
2. $this->_write
3. $this->_read
4. $this->_read

и метода 
- $this->_read();

я так понимаю они должны быть в классе Generic и как сейчас без них работает Demon ?

**Comment by morozovsk** [comment]
Server.php:
        if (!empty($this->config['eventDriver']) && $this->config['eventDriver'] == 'libevent') {
            class_alias('morozovsk\websocket\GenericLibevent', 'morozovsk\websocket\Generic');
        } elseif (!empty($this->config['eventDriver']) && $this->config['eventDriver'] == 'event') {
            class_alias('morozovsk\websocket\GenericEvent', 'morozovsk\websocket\Generic');
        } else {
            class_alias('morozovsk\websocket\GenericSelect', 'morozovsk\websocket\Generic');
        }

**Comment by Sirgalas** [comment]
Спасибо большое.

**Comment by defk** [comment]
Доброго дня!
опять таки с классом morozovsk\websocket\Generic.
в yii2 есть рекомендуемое ими автодополнение (так: https://raw.githubusercontent.com/yiisoft/yii2/master/contrib/completion/bash/yii ), но при добавлении Вашего расширения оно ломается, так как не может найти morozovsk\websocket\Generic
с этим можно что-то сделать?

**Comment by morozovsk** [comment]
одно из двух
1) переписать моё расширение, в частности вот этот код:
```
        if (!empty($this->config['eventDriver']) && $this->config['eventDriver'] == 'libevent') {
            class_alias('morozovsk\websocket\GenericLibevent', 'morozovsk\websocket\Generic');
        } elseif (!empty($this->config['eventDriver']) && $this->config['eventDriver'] == 'event') {
            class_alias('morozovsk\websocket\GenericEvent', 'morozovsk\websocket\Generic');
        } else {
            class_alias('morozovsk\websocket\GenericSelect', 'morozovsk\websocket\Generic');
        }
```
2) переписать расширение для автодополнения, чтобы оно поддерживало конструкцию class_alias
