### ISSUE TITLE
fwrite() failed errno=32

### ISSUE THREAD

**Issue by pzverr** [morozovsk/websocket#21]
Добрый день!
Спасибо за вашу библиотеку.
Подскажите пожалуйста, при использовании библиотеки, довольно часто возникает ошибка:
Notice: fwrite(): send of 1024 bytes failed with errno=32 Broken pipe
Может ли это связано с тем, что я увеличил MAX_SOCKET_BUFFER_SIZE до 262144 ?
И еще, простите за столь нубский вопрос, для чего нужны 'localsocket' => и 'master' =>, в чем отличие от 'websocket' => ?
Спасибо.

**Comment by morozovsk** [comment]
Добрый день.

1) А до увеличения MAX_SOCKET_BUFFER_SIZE всё работало? Нужно по код
смотреть на код. По идее такая ошибка может выдаваться, только если сокет был закрыт, а это автоматически обрабатывается.

2) Вопрос вовсе не нубский. Добавил страницу в документацию: https://github.com/morozovsk/websocket/wiki/master-and-localsocket

**Comment by pzverr** [comment]
Спасибо вам большое за страницу в документацию.
До увеличения не обращал внимание. Я не совсем понимаю суть ошибки, сервер не может установить соединение с сокетом, верно ?

**Comment by morozovsk** [comment]
Ошибка говорит о том, что сервер пытается писать данные в сокет, который разорван.
Попробуйте запустить у себя https://github.com/morozovsk/websocket-examples/tree/master/chatлюбой тестовый пример отсюда https://github.com/morozovsk/websocket-examples, чтобы было понятно ошибка у вас в коде

**Comment by morozovsk** [comment]
видимо я закрыл этот тикет по ошибке

**Comment by pzverr** [comment]
Спасибо.
Проблемы не наблюдал в течении долгого времени с выше указанным примером, скорее всего проблема в изменениях которые, я вносил в код.
Устанавливал черех composer.
