### ISSUE TITLE
how to start 2 websocket servers on 1 VDS

### ISSUE THREAD

**Issue by ryzhak** [morozovsk/websocket#22]
Hello.

Is it possible to run 2 websocket servers on 1 VDS?

I have 2 web applications on 1 VDS. Both of them use your yii2 websocket extension.

To start the 1st websocket server I run:
`cd /var/www/app1`
`./yii websocket/start notificationServer1`

But when I run the 2nd websocket server:
`cd /var/www/app2`
`./yii websocket/start notificationServer2`

then I get "already started" in the console output. I want the 2nd server working as well.

How can I make it work?

config1:
`        'websocket' => [
            'class' => 'morozovsk\yii2websocket\Connection',
            'servers' => [
                'notificationServer1' => [
                    'class' => 'app\modules\v1\modules\notification\components\WebsocketDaemonHandler',
                    'pid' => '/tmp/websocket_chat.pid',
                    'websocket' => 'tcp://127.0.0.1:8004',
                    'localsocket' => 'tcp://127.0.0.1:8010'
                ]
            ],
        ],`

config2:
`        'websocket' => [
            'class' => 'morozovsk\yii2websocket\Connection',
            'servers' => [
                'notificationServer1' => [
                    'class' => 'app\modules\v1\modules\notification\components\WebsocketDaemonHandler',
                    'pid' => '/tmp/websocket_chat.pid',
                    'websocket' => 'tcp://127.0.0.1:8014',
                    'localsocket' => 'tcp://127.0.0.1:8024'
                ]
            ],
        ],`

Hope you got what I mean. Thanks in advance.

**Comment by SergeAx** [comment]
You should use different PIDs for different websocket apps.

**Comment by ryzhak** [comment]
Thank you. I changed 'pid' in the config files and it worked.
