### ISSUE TITLE
Where we write code that run continuously?

### ISSUE THREAD

**Issue by kamalsamra** [morozovsk/websocket#24]

**Comment by morozovsk** [comment]
"nohup php index.php start &"
https://github.com/morozovsk/websocket

**Comment by kamalsamra** [comment]
I know this but in this i have to run one function which is continuously check data from database so in which function i wrote that code like in normal php websocket we write it in **tick function**

**Comment by morozovsk** [comment]
You can use onTimer()
for examle: https://github.com/morozovsk/websocket-examples/blob/master/game/server/GameWebsocketDaemonHandler.php
