### ISSUE TITLE
Как подружить с pg_notify

### ISSUE THREAD

**Issue by ckjet** [morozovsk/websocket#25]
Имеется скрипт следующего содержания:
pg_query($this->connection, 'LISTEN user_notify;');
  while (1) {
    $notify = pg_get_notify($this->connection);
      if ($notify) {
        var_dump(json_decode($notify['payload'], true));
      }
}

Как появляется уведомление в канале user_notify - оно распечатывается. От библиотеки нужно что б она слушала этот канал и как там появлялись данные отсылала по клиентам. Вопрос: как подружить это с библиотекой?

**Comment by morozovsk** [comment]
вот пример, как из стороннего скрипта отправить сообщение  вебсокет-клиенту: https://github.com/morozovsk/websocket-examples/tree/master/chat3/server

**Comment by ckjet** [comment]
Класс Daemon наследуется от Generic, но его в репо нет

**Comment by ckjet** [comment]
Так же не ясно где этот файл
require_once __DIR__ . '/../../../../autoload.php';
Может я что-то упускаю, но не в одном репо их не нашел

**Comment by morozovsk** [comment]
1) autoload.php - это файл композера, сейчас все php-библиотеки перешли на composer
2) Generic - это алиас для нужного класса:
https://github.com/morozovsk/websocket/blob/master/Server.php#L57
