### ISSUE TITLE
GenericEvent считывает не весь буфер

### ISSUE THREAD

**Issue by De-Luxis** [morozovsk/websocket#26]
Если пакет превышает значение константы SOCKET_BUFFER_SIZE, то он не считывает следующую часть, а ждет повторного срабатывания события onRead.

**Comment by morozovsk** [comment]
Да, так и задумано. Происходит равномерное считывание данных со всех соединений. К тому же это единственный способ, который я нашёл, чтобы понять, что доступны данные в буфере соединения иначе бы fread подвисал при попытке считывания пустого буфера до тех пор пока данные придут или таймаут сработает.
Думал использовать для это поле unread_bytes из результатов функции stream_get_meta_data , но там прямо в описании стоит: "Замечание: Вы не должны использовать это значение в скрипте."

**Comment by De-Luxis** [comment]
Ясно. Спасибо за разъяснение.
