### ISSUE TITLE
список онлайн юзеров

### ISSUE THREAD

**Issue by akudryav** [morozovsk/websocket#27]
Есть вопрос, как при подключении/отключении новых юзеров отображать изменения с списке онлайн юзеров? ведь сокет напрямую не связан с javascript на фронте? или можно как-то отправлять сообщения в json формате и обрабатывать отдельно текстовую часть, отдельно данные?

**Comment by morozovsk** [comment]
Не совсем понимаю чем этот функционал отличается от примера:
https://github.com/morozovsk/websocket-examples/tree/master/chat2
демка: http://sharoid.ru/chat2.html

**Comment by akudryav** [comment]
Спасибо, я брал за основу пример chat3 адаптированный для yii.  посмотрю chat2

**Comment by akudryav** [comment]
Если открыть несколько страниц чата одного юзера, то юзер в списке появится несколько раз. Как этого избежать?

**Comment by morozovsk** [comment]
конечно можно. как запрограммируете так и будет. я сделал склейку по имени, вы можете хоть по userId хоть по PHPSESSID

**Comment by akudryav** [comment]
Но ведь в консольном режиме где работает чат сервер нет сессий, откуда брать PHPSESSID фронтенда? передавать в гет параметрах урла обращения к чат серверу? не очень секьюрно получается...

**Comment by morozovsk** [comment]
https://github.com/morozovsk/websocket-examples/blob/master/chat3/server/Chat3WebsocketDaemonHandler.php

**Comment by borodatych** [comment]
Здравствуйте.
Позвольте подниму тему.
Тоже интересует этот вопрос, но еще точнее пинг конкретного пользователя.
Загвоздка стоит именно в реализации на PHP, на JS получается.
На JS я пока просто в userId пишу admin и ему отдаю список при подключение, когда здоровается.
На PHP пробовал разное, что то в этом духе:
```
/// Смиксовал Send и что сгуглилось
$localsocket = 'tcp://127.0.0.1:8010';
$context = stream_context_create();
$instance = stream_socket_client($socketUrl, $errno, $errstr, 10, STREAM_CLIENT_CONNECT, $context);
if( !$instance ) echo "$errstr ($errno)<br />\n";
else
{
    $sent = fwrite( $instance, json_encode( ['message' => $message, 'userId' => $userId] )."\n");
    if( $sent > 0 )
    {
        $server_response = fread($instance, 4096);
        echo $server_response;
    }
}
```
Подключался и к локальному адресу и внешнему, тупо висит пока по таймауту не отпадет.
Подскажите пожалуйста.
Ваша реализация, поэтому сперва к вам.

Спасибо.

**Comment by morozovsk** [comment]
Мало исходных данных, дебажте, создавайте новый тикет, всё подробно описывайте.
