### ISSUE TITLE
Работа в Safari

### ISSUE THREAD

**Issue by akudryav** [morozovsk/websocket#30]
При работе в сафари js выдает ошибкуIndexSizeError (DOM Exception 1): The index is not in the allowed range.
У вас было такое? Можно включить чат сервер на демке, а то не получается протестить...
Кстати заметил что периодически чат сервер самопроизвольно отваливается, с чем это может быть связано?

**Comment by morozovsk** [comment]
Запусти все демки. Периодически - это как часто? По идее должно быть не чаще чем раз в несколько часов в случае неактивности
