### ISSUE TITLE
wss timeot

### ISSUE THREAD

**Issue by ckjet** [morozovsk/websocket#31]
При переезде на https получаю timeout, клиент соединяется через wss://

**Comment by morozovsk** [comment]
https://github.com/morozovsk/websocket/wiki/Together-with-nginx

**Comment by ckjet** [comment]
Опять таймаут
У нас такой конфиг без ssl:
location /websocket {
        #limit_conn perip 5; #set limit to 5 connection from 1 ip
        proxy_pass http://127.0.0.2:8004;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s; #increase timeout to 1 hour
    }

с ssl:
location /websocket {
        #limit_conn perip 5; #set limit to 5 connection from 1 ip
        proxy_pass https://127.0.0.2:8004;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s; #increase timeout to 1 hour
    }

Вот ошибка в логе:upstream prematurely closed connection while reading response header from upstream

**Comment by olegius88** [comment]
Здравствуйте. А вы не замеряли время, за которое отрабатывает ваш код на стороне сервера? может дело в том, что много времени уходит на работу php?

**Comment by ckjet** [comment]
Если использовать http, то все работает, но на https вот так. Не думаю что в этом дело.

**Comment by olegius88** [comment]
а у вас в секции 
server {
    ssl_certificate .ssl/geotrust.amix24.com.crt;
    ssl_certificate_key .ssl/geotrust.amix24.com.key;
}
подобные записи есть? то есть, сам ssl сертификат подключили?

**Comment by ckjet** [comment]
Сертификат подключен и работает.

**Comment by olegius88** [comment]
попробуйте в адресе прописать wss://.../websocket:443

**Comment by ckjet** [comment]
Не помогло

**Comment by morozovsk** [comment]
> Вот ошибка в логе:upstream prematurely closed connection while reading response header from upstream
в логе чего? если в логе nginx, то у вас на указанном ip:port ничего не запущено
возможно вы имели ввиду 127.0.0.1, а не 127.0.0.2 ?

В любом случае нужны полные конфиги для http и https, описать случай в котором всё работает иначе это гадание на кофейной гуще.

Update:
в конфиге с ssl указано: **proxy_pass https://127.0.0.2:8004** , а нужно **http://127.0.0.2:8004**
сама библиотека работает по http, а nginx делает необходимое шифрование.

**Comment by olegius88** [comment]
вот наш рабочий конфиг
location ws {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
        proxy_pass http://127.0.0.1:8013;
        proxy_http_version 1.1;
    }
у нас 127.0.0.1

**Comment by morozovsk** [comment]
ок. скиньте конфиг и опишите случай, в котором у вас работает.
скиньте полный конфиг (с секцие sever  и port), в неработаещем случае
скиньте полный конфиг (с секцие sever  и port), в работаещем случае
кто выдаёт ошибку и какую в случае не работающего

**Comment by ckjet** [comment]
Решил через саму библиотеку, через nginx не получалось

**Comment by olegius88** [comment]
поделитесь

**Comment by ckjet** [comment]
при инициализации я добавил опции:
```
'secure' => true,
 'cert_file' => '/var/www/firstsender/data/ssl_pem/ssl.crt',
'pk_file' => '/var/www/firstsender/data/ssl_pem/ssl.key',
'websocket' => 'ssl://0.0.0.0:8004',
```
Далее в файле Servver.php изменил код на:

```
if (!empty($this->config['websocket'])) {
            //open server socket
            if ($this->config['secure']) {
                $context = stream_context_create();
                if (!is_file($this->config['cert_file'])) {
                    die("Error open cert-file\n");
                }
                if (!is_file($this->config['pk_file'])) {
                    die("Error open key-file\n");
                }
                stream_context_set_option($context, 'ssl', 'local_cert', $this->config['cert_file']);
                stream_context_set_option($context, 'ssl', 'local_pk', $this->config['pk_file']);
                $server = stream_socket_server($this->config['websocket'], $errorNumber, $errorString, STREAM_SERVER_BIND | STREAM_SERVER_LISTEN, $context);
            } else {
                $server = stream_socket_server($this->config['websocket'], $errorNumber, $errorString);
                stream_set_blocking($server, 0);
            }
            if (!$server) {
                die("error: stream_socket_server: $errorString ($errorNumber)\r\n");
            }
        }
```

Долгое время не мог понять почему данные при использовании ssl приходят в виде похожем на бинарный, оказалось что дело было из-за этой строки: stream_set_blocking($server, 0); я ее убрал и все работает отлично.

**Comment by borodatych** [comment]
Конфиг веб-совета:
```
$config = array(
    'class' => 'Backend\Chat\Handler',
    'pid' => '/tmp/websocket_chat.pid',
    'websocket' => 'tcp://80.xx.xx.82:8004',
    'localsocket' => 'tcp://127.0.0.1:8010',
    'eventDriver' => 'event'
);
```

Конфиг Nginx:
```
location /websocket {
        #limit_conn perip 5; #set limit to 5 connection from 1 ip
        proxy_pass http://127.0.0.1:8010;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s; #increase timeout to 1 hour
}
```
Сейчас в консоле браузера:

> WebSocket connection to 'ws://site.ru/websocket?userId=3r3f3b0l09geeevio4c6np55g1_255' failed: Error during WebSocket handshake: Unexpected response code: 404

Что, кстати, указывать в proxy_pass - адрес:порт с websocket или localsocket ?

**Comment by morozovsk** [comment]
> Что, кстати, указывать в proxy_pass - адрес:порт с websocket или localsocket ?
websocket

**Comment by borodatych** [comment]
От себя хочу добавить, что если у кого то не заводится, то попробуйте это реализовать на другом домене/поддомене.
У нас, к примеру, на основном куча всего накручено, и не заработало.
На чистеньком поддомене, все гуд.
