### ISSUE TITLE
stream_select(): supplied argument is not a valid stream resource

### ISSUE THREAD

**Issue by akudryav** [morozovsk/websocket#32]
Периодически возникает ошибка PHP Error[2]: stream_select(): supplied argument is not a valid stream resource
    in file /var/www/ph2/protected/extensions/websocket/GenericSelect.php at line 63
#0 /var/www/ph2/protected/extensions/websocket/GenericSelect.php(63): stream_select()
#1 /var/www/ph2/protected/extensions/websocket/Server.php(84): morozovsk\websocket\Chat3WebsocketDaemonHandler->start()

С чем может быть связано?

**Comment by morozovsk** [comment]
вы вручную в коде соединения закрываете?

**Comment by akudryav** [comment]
Вручную закрываю только если пытаются сделать второй коннект в одной сессии, вот полный код демона:
http://pastebin.com/vxf0zWbP
Остальные классы не менялись, там изначально стоит socket_select.
Можете пояснить как нужно использовать pecl/event?

**Comment by morozovsk** [comment]
поменяйте местами строчки:
$this->sendPacketToClients('logout', $this->online[$connectionId]);
unset($this->online[$connectionId]);

а я добавлю проверку в метод $this->sendToClient($connectionId, $data) чтобы не было попыток отправить данные на несуществующий (или который уже закрыт) сокет.

**Comment by akudryav** [comment]
а в чем фишка? если я сделаю unset, я потеряю номер коннекта и не отображу инфу о логауте юзера.
и как порядок этих строк связан с указанной ошибкой?

**Comment by morozovsk** [comment]
24. `$this->close($connectionId);`
удаляется соединение, но оно по-прежнему есть в массиве $this->online
64. `$this->sendPacketToClients('logout', $this->online[$connectionId]);`
происходит рассылка по всему массиву соединений $this->online (в том числе в то соединение, которое уже было закрыто), об этом и пишет ошибка "supplied argument is not a valid stream resource"
65. `unset($this->online[$connectionId]);`
удаляется соединение из списка $this->online , но уже поздно

если делать `unset($this->online[$connectionId])` то `$connectionId` не теряется, потеряется только если делать `unset($connectionId)`

**Comment by akudryav** [comment]
Спасибо.

**Comment by morozovsk** [comment]
выложил исправленную версию в композер:
https://packagist.org/packages/morozovsk/websocket#4.2.1
