### ISSUE TITLE
Не закрывает соединение при окончании на сайте

### ISSUE THREAD

**Issue by MIKEk8** [morozovsk/websocket#33]
Возможно это так и задумано, но если на сайте делать ws.close то происходит событие onMessage с $type=="close", а событие onClose происходит только после того как сайт прерывает соединение (наверно по тайм ауту).

**Comment by morozovsk** [comment]
onClose - происходит не только по таймауту, но и когда закрывается окно/вкладка.
в описанном случае клиент присылает сообщение на сервер с $type=="close", я его обработку не писал, так же бывают сообщения $type=="ping" и $type=="pong", их обработку я так же не писал. это всё может реализовать пользователь библиотеки.
возможно имеет смысл это всё сделать в самой библиотеке. обещаю об этом подумать.

**Comment by MIKEk8** [comment]
> onClose - происходит не только по таймауту, но и когда закрывается окно/вкладка.
Там оно тоже по таймауту после закрытия вкладки (по крайней мере у меня это происходит именно так)

**Comment by morozovsk** [comment]
я запустил демку http://sharoid.ru/chat2.html в двух браузерах. закрыл вкладку в одном и во втором сразу стало видно, что пользователь пропал

**Comment by MIKEk8** [comment]
Да, это глюк браузера (52.0a2 (2016-12-29) (32-бит) с включённой поддержкой многопроцесорности)
