### ISSUE TITLE
PHP Client

### ISSUE THREAD

**Issue by borodatych** [morozovsk/websocket#37]
Здравствуйте.

Использую https://github.com/morozovsk/websocket-examples/tree/master/chat3

Нужно получить список пользователей через PHP.

Взял текущий файл: https://github.com/morozovsk/websocket-examples/blob/master/chat3/server/send.php

И постарался самостоятельно состряпать, что то вроде:

```
#!/usr/bin/env php
<?php
$socketUrl = 'tcp://127.0.0.1:8010';

$message = "message";
$userId = "k4krmk4k3";

$context = stream_context_create();
$instance = stream_socket_client($socketUrl, $errno, $errstr, 10, STREAM_CLIENT_CONNECT, $context);

if( !$instance ) echo "$errstr ($errno)<br />\n";
else
{
    $sent = fwrite( $instance, json_encode( ['message' => $message, 'userId' => $userId] )."\n");
    if( $sent > 0 )
    {
        $server_response = fread($instance, 4096);
        echo $server_response;
    }
}
```

В данном файле https://github.com/morozovsk/websocket-examples/blob/master/chat3/server/Chat3WebsocketDaemonHandler.php в методе onOpen я добавил условие, и получил такое:
```
protected function onOpen($connectionId, $info) /// Вызывается при соединении с новым клиентом
{
        ///$message = 'пользователь #' . $connectionId . ' : ' . var_export($info, true) . ' ' . stream_socket_get_name($this->clients[$connectionId], true);
        ///foreach( $this->clients as $clientId => $client ) $this->sendToClient($clientId, $message);

        $info['GET']; /// or use $info['Cookie'] for use PHPSESSID or $info['X-Real-IP'] if you use proxy-server like nginx
        parse_str(substr($info['GET'], 1), $_GET);//parse get-query
        ///var_export($_GET['id']);
        $userId = @$_GET['userId'];
        $this->userIds[$connectionId] = $userId;
        if( 'k4krmk4k3'==$userId )
        {
            $message = json_encode(array(
                'clients'=>$this->userIds,
                'info'=>$info,
            ));
            $this->sendToClient($connectionId, $message);
        }
}
```

Через вашего клиента на JS, все гуд, но нужно через PHP.

Конечно на это все не знание и не понимание, но в первую очередь решил обратиться к вам.
Надеюсь поможете с этим вопросом.

Спасибо.

**Comment by morozovsk** [comment]
соединяться надо не с вебсокетом, а локальным сокетом.
ваше условие надо вставлять не в onOpen, а в onServiceMessage.

**Comment by borodatych** [comment]
Хм.. Явно не понимание с моей стороны...

Я ваш [Send](https://github.com/morozovsk/websocket-examples/blob/master/chat3/server/send.php) переделал в свой New, который работает через Web и простым GET запросом вызывается:
```
<?php

$userId = @$_GET['s'];
$message = @$_GET['a'];

if( $userId && $message )
{
    if( 'readNewMsg'==$message )
    {
        $localsocket = 'tcp://127.0.0.1:8010';
        $instance = stream_socket_client ($localsocket, $errno, $errstr);
        fwrite($instance, json_encode( ['message' => $message, 'userId' => $userId] )."\n");
    }
    else die("access denied ....");
}
else die("access denied ...");
```

И все работало, кроме как, не обратил внимание, хотел вернуть ответ "ok" при удачной отправке.
Но "ok" писалось в консоль.
Сейчас удалось получить пинг по пользователю, но так же в консоль.

Создать новый тикет или ответите здесь?
Можно как то через GET или POST запрос файлу отдать ответ, не в консоль имею ввиду?

Попробовал только что так:
```
<?php
$userId = @$_GET['s'];
$message = @$_GET['a'];

if( $userId && $message )
{
    $output = shell_exec(__DIR__."/Send.php $userId $message");
    echo "<pre>$output</pre>";
}
else die("access denied");
```
Все равно в консоль пишет...

**Comment by morozovsk** [comment]
конечно можно, например в примере `chat2` при получении сообщения с `локального сокета` в обработчике `onServiceMessage($connectionId, $packet)` для отправки ответа в это же соединение назад используется `$this->sendToService($connectionId, $packet);`
А считывать ответ в своём скрипте лучше не с помощью `fread($instance, 4096)`, а `fgets($instance)`
https://github.com/morozovsk/websocket-examples/blob/master/chat2/server/Chat2WebsocketMasterHandler.php
