### ISSUE TITLE
Один конект по сокету на несколько вкладок

### ISSUE THREAD

**Issue by borodatych** [morozovsk/websocket#38]
Здравствуйте.

Использую примеры **[Chat3](https://github.com/morozovsk/websocket-examples/tree/master/chat3)**.
Только userId формирую из своих даных.
Случается так, что нужно продублировать вкладку, хотя бы просто что бы запомнить выдачу, а другую обновить и сравнить результат.
Итого одна и та же страница , одни и те же данные для формирования userId и два коннекта по сокету.
Подскажите пожалуйста, можно ли не создавать новые соединение, а вернуть имеющееся, если совпадает userId?

Возможно ответ и есть в коде, но вы свой код знаете лучше, не поймите не правильно.

Спасибо.

**Comment by morozovsk** [comment]
можно, но зачем?
я - бекендер, во фронтэнде не силён, но говорят, что:
1) между вкладками можно обмениваться сообщениями, соответственно можно открываешь сокет в одной, а другие обмениваются с ней сообщениями
2) вебворкер, открываешь сокет в вебворкере, вкладки обмениваются с ней сообщениями

подробнее не подскажу, дальше надо гуглить

все реализации сильно запарные и не стоят экономии лишнего соединения

**Comment by borodatych** [comment]
Решили пока не реализовывать, не тратить время.
Если человек продублировал вкладку значит так надо.
Ответ приходит в ту вкладку от куда задался вопрос, что в принципе логично.
Далее по спросу, что будет просить большинство.
