### ISSUE TITLE
Потраченное время на разработку.

### ISSUE THREAD

**Issue by borodatych** [morozovsk/websocket#39]
Здравствуйте.

Такой вопрос не тривиальный.
Сколько у вас ушло времени на создание рабочего прототипа и примеров с третьим чатом?
Спасибо.

**Comment by morozovsk** [comment]
затрудняюсь ответить. это было 3 года назад. думаю ушло около одного вечера.

**Comment by borodatych** [comment]
Я так понимаю - это и есть [первый комит](https://github.com/morozovsk/websocket/commit/d443e1f8a890b13be836ec6d339e390b2d442fa9) ?
Все остальное чисто марафет?
Если помните, скиньте что читали.
Вечер, это мега быстро, я с вашим решением только 3-5 дней возился, и то один вопрос остался.
А по issue не закрываю, решение если буду искать, то потом его оглашу, тоже так сказать лепту внести.

**Comment by morozovsk** [comment]
нет :) один вечер ушёл только на пример с третьим чатом :)
на прототип ушли две недели новогодних праздников
потом куча времени ушла на написание трёх статей на хабр на эту тему.
потом ещё больше времени на оформление прототипа в библиотеку
потом ещё куча времени на поддержку libevent и event
потом два раза полностью переписал библиотеку с нуля
потом три года на багфикс, техподдержку и т.д. (такое ощущение что на это ушло больше всего времени)
когда начинал, то читал только документацию php.net, пробовал смотреть исходники phpdaemon и ratchet, там внутри всё было на libevent, что никак не добавляло понимания принципов, как это работает.
Когда я делал свою библиотеку, тогда не было особых альтернатив, сейчас же есть, например https://github.com/walkor/Workerman
не тянет зависимостей вообще, в отличие от ratchet, который тянет десятки зависимостей
поддерживает select, libevent, event и ev
есть таймеры.
её автор начал делать свою библиотеку тогда же, когда и я, но в отличие от меня, не просто фиксил баги, а развивал её все три года. в новых проектах я буду использовать её вместо своей библиотеки.

**Comment by borodatych** [comment]
Вашей пока хватает за глаза.
Ту библиотеку тоже добавил в закладки.
Спасибо.
