### ISSUE TITLE
Не сбрасываются коннекты

### ISSUE THREAD

**Issue by borodatych** [morozovsk/websocket#40]
Здравствуйте.

Используем примеры Chat3 и eventDriver=>event.
Со вчерашнего утра и по сегодняшнее коннекты только растут.
На текущий момент 3840.
То есть за ночь не сбросились.
Есть такая проблема и как бороть если есть?
Или это реальные коннекты и радоваться такому обстоятельству дел?

PS: Вопрос бонусом, если нужно создам Issue
В итоге в конфиге осталась одна закомментированная строка:
`//'master' => 'tcp://127.0.0.1:8020',`
Для чего она?

**Comment by morozovsk** [comment]
1) как считаете коннекты?
2) 'master' - используется для соединения с другим процессом посредством сокета в текстовом формате, в Chat2 можно посмотреть пример реализации.

**Comment by borodatych** [comment]
Считается, дак просто, **count($this->userIds)**.

**Comment by morozovsk** [comment]
у меня не было такого кода в примере.
покажите ваш модифицированный код

**Comment by borodatych** [comment]
Handle:

```
protected function onServiceMessage($connectionId, $data)
    {
        $data = json_decode($data);
        $message = @$data->message;
        $action = @$data->action;
        $toUser = @$data->userId;

        if( $action )
        {
            if( 'readNewMsg'==$action )
            {
                $send = "no";
                $message = $action;
                foreach( $this->userIds as $clientId => $userId )
                {
                    if( $toUser == $userId )
                    {
                        $send = "ok";
                        $this->sendToClient($clientId,$message);
                    }
                }
                $this->sendToService($connectionId,json_encode(array('send' => $send)));
            }
            if( 'pingUser'==$action )
            {
                $online = FALSE;
                foreach( $this->userIds as $clientId => $userId )
                {
                    if( $toUser == $userId ) $online = TRUE;
                }
                $this->sendToService($connectionId,json_encode(array('online' => $online)));
            }
            if( 'countUsers'==$action )
            {
                $msg = NULL;
                if( 'full'==$toUser ) $msg = json_encode(array('count' => count($this->userIds),'users' => $this->userIds));
                elseif( 'count'==$toUser ) $msg = count($this->userIds);
                elseif( 'list'==$toUser ) $msg = json_encode($this->userIds);
                $this->sendToService($connectionId,$msg);
            }
        }
        else foreach( $this->userIds as $clientId => $userId ) if( $toUser == $userId ) $this->sendToClient($clientId,$message);
    }
```

**Comment by morozovsk** [comment]
Да вроде правильно, а этот код я надеюсь не удалялся?

> protected function onClose($connectionId) {//it is called when existed connection is closed
        unset($this->userIds[$connectionId]);
    }

**Comment by borodatych** [comment]
На месте)).
Ну значит живые получается.
На текущий момент уже 6188 !!

**Comment by morozovsk** [comment]
а какая дневная посещаемость сайта (сколько уникальных пользователей в день), что столько соединений?

**Comment by olegius88** [comment]
Здравствуйте. Постоянно наблюдаю активные соединения, если было прерывание интернета или если браузер грохнуть в диспетчере задач. Проблему решил посыланием пинга и ожиданием понга по таймеру. если ответ не пришел, убиваю соединение

**Comment by borodatych** [comment]
@olegius88
Если не затруднит, поделитесь скриптиком.
Спасибо

**Comment by borodatych** [comment]
@olegius88
Что вы подразумеваете под словом посылает пинг?
Есть какой то метод?
Или просто маленькое сообщение вы так обозначили?

**Comment by borodatych** [comment]
@morozovsk
Может вы прокомментируете?

**Comment by borodatych** [comment]
Спасибо! Все рабоатет!
