### ISSUE TITLE
"Залипает" при слишком длинном handshake-сообщение (режим event)

### ISSUE THREAD

**Issue by denis-ftc-denisov** [morozovsk/websocket#41]
Проблема в том, что читается один раз до SOCKET_BUFFER_SIZE байт. Если в буфере байт больше, повторно onRead не вызовется и соединение "зависнет".

Лечится заменой в GenericEvent функции _read на такую:
protected function _read($connectionId)
	{
		while (true)
		{
			$data = $this->buffers[$connectionId]->read(self::SOCKET_BUFFER_SIZE);

			if (!strlen($data)) break;

			@$this->_read[$connectionId] .= $data; //add the data into the read buffer
		}
		return strlen($this->_read[$connectionId]) < self::MAX_SOCKET_BUFFER_SIZE;
	}

**Comment by morozovsk** [comment]
спасибо за найденную ошибку, но думаю, что предложенное вами исправление не совсем верное.
В оригинале есть строка `if (!strlen($data)) return;` которую вы изменили, но она очень важная. 
Эта строка обрабатывает событие READ с нулевой длиной, т.е. сокет закрылся, это используется в коде в другом месте `if (is_null($this->_read($connectionId))) { //connection has been closed` Если эту строку убрать, то соединения не будут закрываться на сервере тогда когда оно уже было закрыто на клиенте.

Я склоняюсь к такому коду, который исправит описанные вами и мной проблемы:
> $length = 0;
        while ($data = $this->buffers[$connectionId]->read(self::SOCKET_BUFFER_SIZE)) {
            //add the data into the read buffer
            @$this->_read[$connectionId] .= $data;
            $length += strlen($data);
        }
        return $length > 0 && strlen($this->_read[$connectionId]) < self::MAX_SOCKET_BUFFER_SIZE;
К сожалению у меня сейчас нет тестового стенда, поэтому я не могу проверить этот код, внести изменения в библиотеку и npm.

**Comment by denis-ftc-denisov** [comment]
Добрый день!
Вроде бы если я правильно разобрался, read с нулевой длиной не должен случаться, вместо него должен случиться error.
Впрочем, ваш вариант в любом случае корректно сработает.

**Comment by olegius88** [comment]
Внес в код изменения выше, получил ошибку и сокеты не работали:

PHP Notice:  Undefined offset: 10 in /morozovsk/websocket/GenericEvent.php on line 124
PHP Stack trace:
PHP   1. {main}() /socket.php:0
PHP   2. morozovsk\websocket\Server->restart() /socket.php:103
PHP   3. morozovsk\websocket\Server->start() /morozovsk/websocket/Server.php:137
PHP   4. morozovsk\websocket\GenericEvent->start() /morozovsk/websocket/Server.php:84
PHP   5. EventBase->dispatch() /morozovsk/websocket/GenericEvent.php:50
PHP   6. morozovsk\websocket\GenericEvent->onRead() /morozovsk/websocket/GenericEvent.php:50
PHP   7. morozovsk\websocket\GenericEvent->_readFromBuffer() /morozovsk/websocket/GenericEvent.php:79

**Comment by morozovsk** [comment]
внёс изменения в библиотеку. обновил версию в композере до 4.2.2. ещё раз спасибо за качественное описание бага
>read с нулевой длиной не должен случаться, вместо него должен случиться error.

проверил - всё так :)
