### ISSUE TITLE
Ошибка при остановке

### ISSUE THREAD

**Issue by Valkinaz** [morozovsk/websocket#43]
Здравствуйте.
Большое спасибо за проект, разбираюсь и интегрирую.

Передо мной встала задача ловить pg_get_notify(), поразбиравшись в примерах я решил использовать метод onTimer(). Насколько я понял, принцип работы заключается в запуске дочернего процесса, который через заданный интервал выполняет заданные действия. Судя по всему это то, что надо, однако есть небольшая проблема.

Дело в том, что при выполнении команды `./yii websocket/stop` сервер корректно завершает работу, а вот дочерний процесс похоже остается, и поэтому в консоль выводится ошибка:
```
PHP Notice 'yii\base\ErrorException' with message 'fwrite(): send of 1 bytes failed with errno=32 Broken pipe'
in /var/www/project.zz/vendor/morozovsk/websocket/GenericSelect.php:188
```

Или я ошибаюсь? Это, в принципе, не критично, но есть желание сделать все корректно.
Спасибо.

**Comment by morozovsk** [comment]
да, onTimer создаёт дочерний процесс (если дополнительно не установлена библиотека pecl event), но потом его не убивает. багу я эту так и не пофиксил.

Более того рекомендую использовать https://github.com/walkor/Workerman я сам перешёл на неё (писал об этом на хабре).
А для особенно выкоконагруженных задач рекомендую https://github.com/swoole/swoole-src

**Comment by Valkinaz** [comment]
В тот же день наткнулся Workerman, да, перешел на него. 
Swoole в закладки.
Спасибо
