### ISSUE TITLE
Каково потребление памяти и cpu при нагрузке в 100 000 соединений?

### ISSUE THREAD

**Issue by Levhav** [morozovsk/websocket#45]
Добрый день. У вас заявлена поддерживаемая нагрузка в 100 000 соединений, у вас есть результаты нагрузочного тестирования или хотя бы примерные сведенья о расходе памяти и CPU на каждое соеденение?

**Comment by morozovsk** [comment]
Здравствуйте. Если ещё не выбрали решение, то рекомендую Workerman или Swoole. Моя библиотека больше не поддерживается.

**Comment by Levhav** [comment]
Я занимаюсь разработкой своего решения на С++ https://github.com/CppComet/comet-server и мне стало интересно насколько моё решение эффективно по сравнению с аналогами. 
У меня на 64 000 соединений уходит примерно 5гб памяти. Но не понятно много это или мало так как не счем соравнить.

**Comment by Levhav** [comment]
Я сейчас рассматриваю возможность доработки апи своего решения чтобы оно смогло работать с кодом написанным дляя решений типа Workerman или чего то подобного. Пытаюсь понять будет ли это восстребованным и пропорционально ли это тем услиям которые потребуются на такие доработки. 
Но сам я не разу не использовал что то аналогичное Workerman.

**Comment by morozovsk** [comment]
Извиняюсь, что долго не отвечал. Участвую в https://highloadcup.ru/
Локально запускать и считать лень, поэтому просто процитирую само себя в прошлом:
"около 90 мб на 10к соединений, т.е. 9кб на одно соединение"
https://habrahabr.ru/post/209864/#comment_7234220

>У меня на 64 000 соединений уходит примерно 5гб памяти. 

5гб - это однозначно очень много
