### ISSUE TITLE
Почему бросили?

### ISSUE THREAD

**Issue by nnrudakov** [morozovsk/websocket#46]
@morozovsk 
> This library works, but I will not develop and support it because I will use https://github.com/walkor/Workerman

почему бросили и почему именно Workerman? библиотека прям намного менее монстроузна, чем ratchet?

**Comment by morozovsk** [comment]
Вот моя статья на эту тему: https://habr.com/post/331462/

**Comment by nnrudakov** [comment]
спасибо
