### ISSUE TITLE
EventListener callback

### ISSUE THREAD

**Issue by Chameleon-m** [morozovsk/websocket#5]
В этом методе https://github.com/morozovsk/websocket/blob/master/WebsocketGenericEvent.php#L51 , вы параметр $connection обрабатываете с помощью $this->getIdByConnection($connection);
Вопрос : В каких случаях $connection не int ?

Мой дамп при конекте:
```php
var_dump([$listener, $connection, $address, $id]);

array(4) {
  [0]=>
  object(EventListener)#5 (1) {
    ["fd"]=> int(3)
  }
  [1]=> int(7)
  [2]=>
  array(2) {
    [0]=> string(9) "127.0.0.1"
    [1]=> int(60314)
  }
  [3]=>
  object(EventBase)#4 (0) {
  }
}
```

**Comment by morozovsk** [comment]
проверил, операция была лишняя, ни на что не влияла, но всё равно поправил
