### ISSUE TITLE
Локальный сокет

### ISSUE THREAD

**Issue by cbv-k** [morozovsk/websocket#7]
Здравствуйте!
Не нашел, как можно лично задать вам вопрос.
Попытался реализовать у себя сокет на примере первого чата. Не получается установить с ним подключение по сокету unix:///tmp/websocket.sock, про который вы говорите в статье http://habrahabr.ru/company/ifree/blog/210228/.
Например, пишу в index.php 'localsocket' => 'unix:///var/www/websocket.sock' , затем пытаюсь передать данные:
$fp = stream_socket_client("unix:///var/www/websocket.sock", $errno, $errstr, 30);
if (!$fp) {
    echo "$errstr ($errno)<br />\n";
} else {
    fwrite($fp, "vsem privet"."\r\n");
    while (!feof($fp)) {
        echo fgets($fp, 1024);
    }
    fclose($fp);
}
Пишет, доступ запрещен, меняю права на 777, скрипт долго выполняется, но ничего не передается. Подскажите, пожалуйста, что я не так делаю?

Еще подскажите, пожалуйста, правильно ли я понимаю, уязвимости, про которые вам писали в комментариях, есть в первом чате, но исправлены во втором?

**Comment by morozovsk** [comment]
Здравствуйте. С юникс-сокетами потенциально много проблема (права и т.д.), по этому рекомендую использовать дефолтный конфиг из первого чата:
$config = array(
    'class' => 'ChatWebsocketDaemonHandler',
    'pid' => '/tmp/websocket_chat.pid',
    'websocket' => 'tcp://127.0.0.1:8000',
    //'localsocket' => 'tcp://127.0.0.1:8010',
    //'master' => 'tcp://127.0.0.1:8020',
    //'eventDriver' => 'event'
);
И первый и второй чат использует вторую версию библиотеки, отличие межу чатами в том, что для второго чата нужно запуск двух скриптов (мастер и воркер), что можно использовать для масштабирования (1 мастер и много воркеров).

Рекомендую использовать первый чат, он проще заводится: https://github.com/morozovsk/websocket/tree/master/samples/chat

**Comment by cbv-k** [comment]
Большое спасибо за столь оперативный ответ!
Сейчас у меня в настройках:
'websocket' => 'tcp://домен:8000'
С внешних серверов все прекрасно работает.
Но когда я пытаюсь передать локально на сокет данные, чтобы отправить их всем подключенным клиентам - скрипт долго загружается, при этом ничего не происходит, и я не получаю никаких ошибок на сервере. Использую данный скрипт:
$fp = stream_socket_client("tcp://домен:8000", $errno, $errstr, 30);
if (!$fp) {
    echo "$errstr ($errno)<br />\n";
} else {
    fwrite($fp, "vsem privet"."\r\n");
    while (!feof($fp)) {
        echo fgets($fp, 1024);
    }
    fclose($fp);
}
В чем может быть проблема?
Вообще, мне нужно передать данные, получаемые при помощи гет-запроса, всем подключенным к сокету, может есть какой-то иной способ?

**Comment by morozovsk** [comment]
в конфиге нужно добавить:
'localsocket' => 'tcp://127.0.0.1:8010'
и открывать соединение на него, потому что при подключении к 'websocket' => 'tcp://домен:8000'
также нужно добавить обработчик сообщений на локальном сокете.
Например этот будет рассылать всем клиентам вебсокета сообщения полученные по локальному сокету:
protected function onServiceMessage($connectionId, $data) {
        foreach ($this->clients as $clientId => $client) {
            $this->sendToClient($clientId, $data);
        }
    }

**Comment by cbv-k** [comment]
Огромное спасибо, все заработало!
