### ISSUE TITLE
How can simply build Websocket server on a http domain?

### ISSUE THREAD

**Issue by williamesp2015** [morozovsk/websocket#8]
Could you please provide instuction for a websocket server to show in a log windows messages sent from different clients with their IP and sending message to each of clients with http or www domain name.TQ

**Comment by morozovsk** [comment]
use pls httpssample "chat3" ://github.com/morozovsk/websocket/tree/master/samples/chat3
websocket server port: 8004 - for websocket clients
local socket port: 8010 - for scripts like send.php

**Comment by williamesp2015** [comment]
Thank you. Unfortunately the link does not work. Please provide an updated link to chat3.

**Comment by morozovsk** [comment]
https://github.com/morozovsk/websocket-examples/tree/master/chat3
